require("nvim-treesitter").setup({
	parser_install_dir = vim.fn.stdpath("data") .. "/site",
	auto_install = true,
	ensure_installed = {
		"bash",
		"cpp",
		"css",
		"dockerfile",
		"gdscript",
		"git_rebase",
		"gitattributes",
		"gitcommit",
		"gitignore",
		"go",
		"gomod",
		"gosum",
		"groovy",
		"html",
		"hyprlang",
		"java",
		"javascript",
		"json",
		"lua",
		"markdown",
		"markdown_inline",
		"nix",
		"properties",
		"python",
		"requirements",
		"scss",
		"toml",
		"typescript",
		"vim",
		"vimdoc",
		"vue",
		"xml",
		"yaml",
	},
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = false,
	},
	incremental_selection = {
		enable = true,
	},
	-- context commetstring setup
	-- source: https://github.com/JoosepAlviste/nvim-ts-context-commentstring#commentnvim
	context_commentstring = {
		enable = true,
		enable_autocmd = false,
	},
})
